### ISSUE TITLE
gitbook build failures

### ISSUE THREAD

**Issue by hez** [sandrinodimattia/gitbook-express-auth0-boilerplate#2]
I managed to get this working locally but deploying with the same versions to heroku is failing.

nodejs ver: 11.6.0

We get the following error when the "gitbook build" command gets executed
```
-----> Build
       Running build
       
       > pxu-guide-gitbook@1.0.0 build /tmp/build_3e9d92687f9f4b5283e7ec1deaa79896
       > gitbook build ./content/
       
       Installing GitBook 3.2.3
evalmachine.<anonymous>:25
'use strict';
^
ReferenceError: internalBinding is not defined
    at evalmachine.<anonymous>:25:1
    at Object.<anonymous> (/tmp/build_3e9d92687f9f4b5283e7ec1deaa79896/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/tmp/build_3e9d92687f9f4b5283e7ec1deaa79896/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/graceful-fs.js:3:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pxu-guide-gitbook@1.0.0 build: `gitbook build ./content/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pxu-guide-gitbook@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.wjVc7/_logs/2019-03-06T18_54_53_882Z-debug.log
```

Any ideas?

**Comment by hez** [comment]
We actually ended up solving this by updating all the libraries to newer versions.


Keep up the good work!
